apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: rancher-transport
  namespace: traefik
spec:
  insecureSkipVerify: true
  forwardingTimeouts:
    dialTimeout: 30s
    responseHeaderTimeout: 0s
    requestTimeout: 1800s
    idleConnTimeout: 0s
