apiVersion: v1
kind: Service
metadata:
  name: rancher-external
  namespace: traefik
  labels:
    app.kubernetes.io/name: rancher
spec:
  type: ExternalName
  externalName:   
  ports:
    - port: 31453
      targetPort: 31453
      protocol: TCP
      name: https
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: rancher-route
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`rancher.philippmhauptmann.me`)
      middlewares:
        - name: rancher-x-forwarded-proto
        - name: ratelimit
        - name: cloudflare-ip-whitelist
        - name: secure-headers
      kind: Rule
      services:
        - name: rancher-external
          port: 31453
          passHostHeader: true
  tls:
    certResolver: cloudflare
