apiVersion: v1
kind: Service
metadata:
  name: vaultwarden-external
  namespace: traefik
  labels:
    app.kubernetes.io/name: vaultwarden
spec:
  type: ExternalName
  externalName: 192.168.0.129
  ports:
    - port: 30032
      targetPort: 30032
      protocol: TCP
      name: http
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: vaultwarden-route
  namespace: traefik
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`vault.philippmhauptmann.me`)
      middlewares:
        - name: ratelimit
        - name: cloudflare-ip-whitelist
        - name: secure-headers
      kind: Rule
      services:
        - name: vaultwarden-external
          port: 30032
          passHostHeader: true
  tls:
    certResolver: cloudflare
