hostname: rancher.philippmhauptmann.me

replicas: 1

ingress:
  enabled: false

tls: external

service:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      name: http
      nodePort: 30080
      targetPort: 80
    - port: 443
      protocol: TCP
      name: https-internal
      nodePort: 30443
      targetPort: 444
