hostname: rancher.philippmhauptmann.me

replicas: 1

ingress:
  enabled: true
  includeDefaultExtraAnnotations: true
  extraAnnotations: 
    traefik.ingress.kubernetes.io/router.tls.certresolver: cloudflare
  ingressClassName: "traefik"

tls: external

service:
  type: NodePort
