hostname: rancher-internal.philippmhauptmann.me

replicas: 1

ingress:
  enabled: true
  includeDefaultExtraAnnotations: true
  #extraAnnotations: {}
  ingressClassName: "traefik"
  annotations: {}
  pathType: ImplementationSpecific
  path: "/"


tls: external
