defaultSettings:
  defaultReplicaCount: "2"

persistence:
  defaultClass: true
  defaultClassReplicaCount: 2

ingress:
  enabled: false

csi:
  attacherReplicaCount: "2"
  provisionerReplicaCount: "2"
  resizerReplicaCount: "2"
  snapshotterReplicaCount: "2"
