replica:
  allNodes: false

tunnelSecrets:
  existingConfigJsonFileSecret:
    name: cloudflare-tunnel-secret
    key: credentials.json
  existingPemFileSecret:
    name: cloudflare-tunnel-secret
    key: cert.pem
tunnelConfig:
  # -- cloudflared tunnel name
  name: "strassgang-tunnel"
  metricsUpdateFrequency: 5s
  autoUpdateFrequency: 24h
  noAutoUpdate: false
  gracePeriod: 30s
  retries: 5
  # auto, http2, h2mux, quic
  protocol: auto
  # info, warn, error, fatal, panic
  logLevel: info
  transportLogLevel: warn
  connectTimeout: 30s
  warpRouting: false

ingress:
#  - hostname: s3.philippmhauptmann.me
#    service: http://seaweedfs-s3.seaweedfs.svc.cluster.local:8333

  - hostname: "*.philippmhauptmann.me"
    service: https://traefik.traefik.svc.cluster.local:443
    originRequest:
      originServerName: "*.philippmhauptmann.me"
      matchSNItoHost: true
  - hostname: "*.hauptmann.dev"
    service: https://traefik.traefik.svc.cluster.local:443
    originRequest:
      originServerName: "*.hauptmann.dev"
      matchSNItoHost: true
  - service: http_status:404
